from yacs.config import CfgNode as CN

_C = CN()

_C.INPUT = CN()

_C.INPUT.SOURCE = ''

_C.LOGGING = CN()

_C.LOGGING.ENABLE_LOGGING = True
_C.LOGGING.LOG_DIR = 'data/logs/'
_C.LOGGING.LOG_INTERVAL = 10

_C.TRAINING = CN()

_C.TRAINING.NUM_CHANNELS = 1
_C.TRAINING.SAVE_MODEL_STEP = 10

_C.TRAINING.ONLY_SAVE_FEATURES = False
_C.TRAINING.AUGMENTATION = False
_C.TRAINING.WITH_VAR_LOSS = True

_C.TRAINING.MODEL = ''
_C.TRAINING.MODEL_DIR = ''
_C.TRAINING.REPRESENTATIONS_DIR = ''

_C.TRAINING.EXPERIMENT_NAME = ''
_C.TRAINING.TRAINING_SET = 'us3d'

_C.TRAINING.NUM_WORKERS = 8
_C.TRAINING.PIN_MEMORY = True

_C.TRAINING.RESUME = ''
_C.TRAINING.START_EPOCH = 0
_C.TRAINING.EPOCHS = 50

_C.TRAINING.BATCH_SIZE = 4
_C.TRAINING.TEST_BATCH_SIZE = 4

_C.TRAINING.LOSS = 'initial'

_C.TRAINING.BASE_LR = 0.001
_C.TRAINING.LR_DECAY = 1e-6
_C.TRAINING.W_DECAY = 1e-4
_C.TRAINING.MOMENTUM = 0.9

_C.TRAINING.OPTIMIZER = 'Adam'

_C.TRAINING.AUG = False

_C.TRAINING.CUDA = True
_C.TRAINING.GPU_ID = 3

_C.TRAINING.SEED = 42
_C.TRAINING.RESBLOCK_NUM = 1
_C.TRAINING.DISPBLOCK_NUM = 1
_C.TRAINING.MAXDISP = 16
_C.TRAINING.DISPSPACE = 'two-sided'
_C.TRAINING.WIDTH = 512
_C.TRAINING.HEIGHT = 256

_C.TEST = CN()

_C.TEST.CUDA = True
_C.TEST.BATCH_SIZE = 4
_C.TEST.MODEL_WEIGHTS = ''