INPUT:
  SOURCE: 'D:\Datasets\dislocations\ALL_DATA_fixed_bottom_resized\'

LOGGING:

  ENABLE_LOGGING: True
  LOG_DIR: 'D:\Logs\'
  LOG_INTERVAL: 1

TRAINING:

  ONLY_SAVE_FEATURES: False
  MODEL_DIR: 'D:\Models\dislocations\'
  SAVE_MODEL_STEP: 10
  AUGMENTATION: True

  LOSS: 'bce'

  EXPERIMENT_NAME: 'dislocations_segmentation_unet'
  TRAINING_SET: 'dislocations' # possible 'us3d', 'dislocations'
  NUM_CHANNELS: 1

  NUM_WORKERS: 4
  PIN_MEMORY: True

  RESUME: ''
  START_EPOCH: 0
  EPOCHS: 150

  BATCH_SIZE: 2
  TEST_BATCH_SIZE: 2

  BASE_LR: 0.001
  LR_DECAY: 1e-6
  MOMENTUM: 0.9

  W_DECAY: 1e-4
  OPTIMIZER: 'Adam'

  AUG: False

  CUDA: True
  GPU_ID: 1

  SEED: 42

TEST:

  BATCH_SIZE: 4
  CUDA: True
  MODEL_WEIGHTS: ''