INPUT:
  SOURCE: 'D:\Datasets\dislocations\ALL_DATA_fixed_bottom_resized\'

LOGGING:

  ENABLE_LOGGING: True
  LOG_DIR: 'D:\Logs\'
  LOG_INTERVAL: 1

TRAINING:

  ONLY_SAVE_FEATURES: False
  MODEL: 'unet,scmnet_seg'
  MODEL_DIR: 'D:\Models\dislocations\'
  SAVE_MODEL_STEP: 10
  AUGMENTATION: True

  LOSS: 'smooth_l1_masked_disparity'

  EXPERIMENT_NAME: 'dislocations_matching_scmnet_seg'
  TRAINING_SET: 'dislocations_matching' # possible 'us3d', 'dislocations'
  NUM_CHANNELS: 1

  NUM_WORKERS: 4
  PIN_MEMORY: True

  RESUME: ','
  START_EPOCH: 0
  EPOCHS: 150

  BATCH_SIZE: 2
  TEST_BATCH_SIZE: 2

  BASE_LR: 0.0001
  LR_DECAY: 1e-6
  MOMENTUM: 0.9

  W_DECAY: 1e-4
  OPTIMIZER: 'Adam'

  AUG: False

  CUDA: True
  GPU_ID: 1

  SEED: 42
  RESBLOCK_NUM: 2
  DISPBLOCK_NUM: 1
  MAXDISP: 16
  DISPSPACE: 'two-sided'
  WIDTH: 512
  HEIGHT: 256

TEST:

  BATCH_SIZE: 4
  CUDA: True
  MODEL_WEIGHTS: 'D:\Models\dislocations\dislocations_segmentation_unet\150_segmentor.tar,'